version: 1.0.{build}
os: Visual Studio 2015
environment:
  WHEEL_DIR: C:\kivy_wheels
  KIVY_BUILD_DIR: C:\kivy_build
  DO_WHEEL: True
  USE_SDL2: 1
  USE_GSTREAMER: 1
  KIVY_USE_SETUPTOOLS: 1
  KIVY_SPLIT_EXAMPLES: 1
  MSYSTEM: MINGW64
  CHERE_INVOKING: 1
  matrix:
  - PYVER: 27
    BITTNESS: 86
    COMPILER: mingw
  - PYVER: 27
    BITTNESS: 64
    COMPILER: mingw
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
build_script:
- nuget install secure-file -ExcludeVersion
- ps: |
    function Check-Error
    {
      param([int]$SuccessVal = 0)
      if ($SuccessVal -ne $LastExitCode) {
        throw "Failed with exit code $LastExitCode"
      }
    }
    echo "Bitness=$env:BITTNESS, scheduled=$env:APPVEYOR_SCHEDULED_BUILD, forced=$env:APPVEYOR_FORCED_BUILD, rebuild=$env:APPVEYOR_RE_BUILD, tagged=$env:APPVEYOR_REPO_TAG"
    cd $env:APPVEYOR_BUILD_FOLDER
    git clone -q --branch=master https://github.com/kivy/kivy-sdk-packager.git C:\projects\kivy-sdk-packager
    Check-Error
    $PYTHONPATH = "$env:APPVEYOR_BUILD_FOLDER;$PYTHONPATH"
    C:\Python27\Scripts\pip.exe install pydrive
    Check-Error
    if ($env:BITTNESS -eq "64") {
      $PYTHON_ROOT = "C:\Python$env:PYVER-x64"
      $WHELL_BITNESS = "win_amd64"
    } else {
      $PYTHON_ROOT = "C:\Python$env:PYVER"
      $WHELL_BITNESS = "win32"
    }
    $env:PATH = "$PYTHON_ROOT;$PYTHON_ROOT\Scripts;$env:PATH;C:\Program Files\7-Zip"
    $env:PATH = $PYTHON_ROOT+"\share\glew\bin;"+$PYTHON_ROOT+"\share\sdl2\bin;"+$PYTHON_ROOT+"\share\gstreamer\bin;"+$env:PATH
    Check-Error
    python -m pip install pip wheel setuptools --upgrade
    Check-Error
    if ($env:COMPILER -ne "msvc") {
      python -c "with open(r'$PYTHON_ROOT\Lib\distutils\distutils.cfg', 'wb') as fh: fh.write(b'[build]\ncompiler = mingw32\n')"
      Check-Error
      pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy
      Check-Error
    }
    pip install mock cython pygments docutils nose kivy.deps.glew_dev kivy.deps.glew kivy.deps.gstreamer_dev kivy.deps.sdl2_dev kivy.deps.sdl2
    pip --no-cache-dir install kivy.deps.gstreamer
    Check-Error
    pip install kivy pyinstaller
    Check-Error
    python -m PyInstaller --name memgame ./main.py
    python -m PyInstaller memgame.win.spec
    7z a memgame.zip ./dist/memgame
artifacts:
  - path: memgame.zip
    name: Memgame